name: bits
description: Write in bits instead of bytes for packing data tighter, and increasing headaches.
version: 1.3.1
homepage: https://github.com/ArcaneArts/bits
environment:
  sdk: '>=2.18.6 <3.0.0'
dependencies:
  crypto: ^3.0.2
  threshold: ^1.0.3
dev_dependencies:
  test: ^1.22.2
