name: bits
description: Write in bits instead of bytes for packing data tighter, and increasing headaches.
version: 1.0.0
homepage: https://github.com/ArcaneArts/bits
environment:
  sdk: '>=2.18.6 <3.0.0'
dependencies:
  threshold: ^1.0.0
